id: P009620
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5135
  title: ཤེར་ཕྱིན་སྒོམ་རིམ་དང་སྨྱུང་གནས་ཕན་ཡོན།༼ཀུན་ཕན་ཞི་བདེའི་དཔེ་ཚོགས།
  author: ''
  volumes:
    34cc35d650a94b49846d30abf1742e4d:
      image_group_id: I3CN5137
      title: ''
      volume_number: 1
      total_pages: 344
      base_file: v001.txt
